version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    env_file:
      - ./api/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:16-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./api/.env